# Generated by Django 3.0.6 on 2020-06-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500, null=True)),
                ('file_type', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField()),
                ('uploaded_file', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message_body', models.CharField(max_length=500)),
                ('group_flag', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1000)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=35)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaboverideas.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(max_length=20)),
                ('user', models.ManyToManyField(to='collaboverideas.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserInvites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100)),
                ('invite_flag', models.BooleanField(default=0)),
                ('passcode', models.CharField(max_length=100)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.Teams')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='user',
            field=models.ManyToManyField(to='collaboverideas.User'),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=1000)),
                ('due_date', models.DateField()),
                ('list_id', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('label', models.ManyToManyField(to='collaboverideas.Labels')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.Teams')),
                ('user', models.ManyToManyField(to='collaboverideas.User')),
            ],
        ),
        migrations.CreateModel(
            name='Snippets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('code', models.BinaryField()),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.Teams')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.User')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status_flag', models.BooleanField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.Message')),
                ('recipient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='collaboverideas.User')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.Teams'),
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('meeting_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('invitees', models.ManyToManyField(to='collaboverideas.User')),
                ('scheduler', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to='collaboverideas.User')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.Teams')),
            ],
        ),
        migrations.AddField(
            model_name='labels',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.Teams'),
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collaboverideas.File')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaboverideas.Teams')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaboverideas.User')),
            ],
        ),
    ]
